// Run this file once to populate your database with existing products
// Command: node seedProducts.js

require('dotenv').config();
const { sequelize, connectDB } = require('./config/db');
const Product = require('./models/productModel');

const productsData = [
    // Sweets
    { id: 'sw1', name: 'Kova Garijalu', teluguName: 'కోవా గరిజలు', category: 'Sweets', basePrice: 450, price250g: 113, price500g: 225, price1kg: 450, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/c_pad,b_gen_fill,ar_4:3/v1760471610/kova_gari_lr2lzt.webp', description: 'Sweet, crispy pastries filled with a rich kova and coconut mixture.', teluguDescription: 'కొబ్బరి మరియు కోవాతో నింపిన తీపి, కరకరలాడే గరుజలు, పండుగలకు సరైనవి.', stock: 100 },
    { id: 'sw2', name: 'Putnala Garijalu', teluguName: 'పుట్నాల గరిజలు', category: 'Sweets', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760471931/putnaa_gari_m4ugln.webp', description: 'Traditional sweet pastries filled with roasted gram dal.', teluguDescription: 'పుట్నాల పప్పుతో చేసిన సాంప్రదాయ తీపి గరుజలు, రుచికరమైనవి మరియు ఆరోగ్యకరమైనవి.', stock: 100 },
    { id: 'sw3', name: 'Nuvvula Garijalu', teluguName: 'నువ్వుల గరిజలు', category: 'Sweets', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760472219/nuvvvi_gari_xfkoei.png', description: 'Sweet pastries made with sesame seeds and jaggery, offering a nutty flavor.', teluguDescription: 'నువ్వులు మరియు బెల్లంతో చేసిన తీపి గరుజలు, పోషకాలతో నిండి ఉంటాయి.', stock: 100 },
    { id: 'sw4', name: 'Bobbatlu', teluguName: 'బొబ్బట్లు', category: 'Sweets', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760472196/bobba_glq8qu.png', description: 'Soft, sweet flatbreads filled with a delicious mixture of lentils and jaggery.', teluguDescription: 'శనగపప్పు మరియు బెల్లంతో నింపిన మృదువైన, తీపి బొబ్బట్లు, పండుగల స్పెషల్.', stock: 100 },
    { id: 'sw5', name: 'Sweet Gavvalu', teluguName: 'తీపి గవ్వలు', category: 'Sweets', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760472646/sweet_gavva_md1jeh.png', description: 'Shell-shaped sweet snacks, deep-fried and glazed with jaggery syrup.', teluguDescription: 'బెల్లం పాకంలో ముంచిన తీపి గవ్వలు, పిల్లలు ఎంతో ఇష్టపడే చిరుతింది.', stock: 100 },
    { id: 'sw6', name: 'Nuvvula Laddu', teluguName: 'నువ్వుల లడ్డు', category: 'Sweets', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760473748/nuvvu_laddu_nbbhzm.webp', description: 'Nutritious spheres made from roasted sesame seeds and jaggery.', teluguDescription: 'నువ్వులు, బెల్లం మరియు నెయ్యితో చేసిన ఆరోగ్యకరమైన మరియు రుచికరమైన లడ్డూలు.', stock: 100 },
    { id: 'sw7', name: 'Palli Laddu', teluguName: 'పల్లి లడ్డు', category: 'Sweets', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760473579/palli_wge7dy.webp', description: 'Traditional spheres made from roasted peanuts and jaggery, packed with energy.', teluguDescription: 'వేయించిన పల్లీలు మరియు బెల్లంతో చేసిన సాంప్రదాయ లడ్డూ, శక్తిని అందిస్తుంది.', stock: 100 },
    { id: 'sw8', name: 'Laddu', teluguName: 'లడ్డు', category: 'Sweets', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760473826/laddu_swubzs.webp', description: 'Classic sweet spheres made from gram flour, ghee, and sugar.', teluguDescription: 'శనగపిండితో చేసిన మృదువైన మరియు తీపి లడ్డూలు, ప్రతి శుభకార్యానికి ప్రత్యేకం.', stock: 100 },
    { id: 'sw9', name: 'Arshalu (Bellam)', teluguName: 'అరిసెలు (బెల్లం)', category: 'Sweets', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760473961/bellam_ariselu_oaiutr.webp', description: 'Traditional rice flour cakes sweetened with jaggery, a festive delicacy.', teluguDescription: 'బియ్యం పిండి మరియు బెల్లంతో చేసిన సాంప్రదాయ అరిసెలు, పండుగ విందులో భాగం.', stock: 100 },
    { id: 'sw10', name: 'Arshalu (Sugar)', teluguName: 'అరిసెలు (చక్కెర)', category: 'Sweets', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760474319/sugar_ariselu_tjx9hu.webp', description: 'Sweet rice flour cakes made with sugar syrup for a distinct taste.', teluguDescription: 'చక్కెర పాకంతో చేసిన తీపి అరిసెలు, విభిన్నమైన రుచిని అందిస్తాయి.', stock: 100 },
    { id: 'sw11', name: 'Badusha', teluguName: 'బాదుషా', category: 'Sweets', basePrice: 300, price250g: 75, price500g: 150, price1kg: 300, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760475105/badha_obshyu.webp', description: 'A flaky, layered pastry soaked in sugar syrup, a classic Indian sweet.', teluguDescription: 'మైదా పిండితో చేసి, చక్కెర పాకంలో ముంచిన మెత్తటి బాదుషాలు, నోరూరించే తీపి.', stock: 100 },
    
    // Snacks
    { id: 'sn1', name: 'Chegodilu', teluguName: 'చెగోడీలు', category: 'Snacks', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760474383/chegodi_jxw6gc.webp', description: 'Crunchy, ring-shaped snacks made from rice flour and sesame seeds.', teluguDescription: 'బియ్యం పిండి మరియు నువ్వులతో చేసిన కరకరలాడే చెగోడీలు, టీ సమయానికి సరైనవి.', stock: 100 },
    { id: 'sn2', name: 'Vadaapalu', teluguName: 'వడపపు', category: 'Snacks', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760475122/vada_x6quxb.webp', description: 'Crispy vadas made from lentils, a popular savory snack.', teluguDescription: 'మినపప్పుతో చేసిన రుచికరమైన వడలు, పండుగలు మరియు ప్రత్యేక సందర్భాలలో తప్పనిసరి.', stock: 100 },
    { id: 'sn3', name: 'Sakinalu', teluguName: 'సకినాలు', category: 'Snacks', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760475820/saki_mhymtm.webp', description: 'Traditional Telangana snack made of concentric circles of rice flour dough.', teluguDescription: 'తెలంగాణ సాంప్రదాయ పిండివంట, బియ్యం పిండి మరియు నువ్వులతో చేసిన కరకరలాడే సకినాలు.', stock: 100 },
    { id: 'sn4', name: 'Karam Sakinalu', teluguName: 'కారం సకినాలు', category: 'Snacks', basePrice: 350, price250g: 88, price500g: 175, price1kg: 350, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760475943/karam_sakinalu_avahiu.webp', description: 'A spicy version of the traditional Sakinalu, for those who like a kick.', teluguDescription: 'కారం మరియు మసాలాలతో చేసిన ఘాటైన సకినాలు, స్పైసీగా ఇష్టపడేవారికి ప్రత్యేకం.', stock: 100 },
    { id: 'sn5', name: 'Muruku', teluguName: 'మురుకులు', category: 'Snacks', basePrice: 320, price250g: 80, price500g: 160, price1kg: 320, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760475590/murkulu_tbuynv.webp', description: 'A crunchy, savory snack made from rice flour and urad dal flour.', teluguDescription: 'బియ్యం పిండి మరియు శనగపిండితో చేసిన కరకరలాడే మురుకులు, సాయంత్రం స్నాక్‌గా అద్భుతం.', stock: 100 },
    { id: 'sn6', name: 'Pusa', teluguName: 'పూస', category: 'Snacks', basePrice: 300, price250g: 75, price500g: 150, price1kg: 300, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760476237/pusa_tygrgv.webp', description: 'Thin, crispy strands made from gram flour, a key ingredient in many mixtures.', teluguDescription: 'శనగపిండితో చేసిన సన్నని, కరకరలాడే పూస, మిక్చర్లలో మరియు విడిగా తినడానికి బాగుంటుంది.', stock: 100 },
    { id: 'sn7', name: 'Karam Gavvalu', teluguName: 'కారం గవ్వలు', category: 'Snacks', basePrice: 320, price250g: 80, price500g: 160, price1kg: 320, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760476357/kaaram_gavvlu_l5vtvf.webp', description: 'Spicy, shell-shaped snacks made from wheat flour, perfect for a savory crunch.', teluguDescription: 'గోధుమ పిండితో చేసిన, కారంగా ఉండే గవ్వలు, కరకరలాడుతూ చాలా రుచిగా ఉంటాయి.', stock: 100 },
    { id: 'sn8', name: 'Karam Bondi', teluguName: 'కారం బూంది', category: 'Snacks', basePrice: 320, price250g: 80, price500g: 160, price1kg: 320, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/c_pad,b_gen_fill,w_1600,h_1200/v1753899025/BONDI_aa33vb.png', description: 'Spicy, crispy pearls made from gram flour, a festive favorite.', teluguDescription: 'శనగపిండితో చేసిన కారంగా ఉండే బూంది, పండుగలకు మరియు విందులకు ప్రత్యేకం.', stock: 100 },
    { id: 'sn9', name: 'Kaju Pakoda', teluguName: 'కాజు పకోడీ', category: 'Snacks', basePrice: 1000, price250g: 250, price500g: 500, price1kg: 1000, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760508548/kaju_prrvic.webp', description: 'Delicious pakodas made with cashews and a spiced gram flour batter.', teluguDescription: 'జీడిపప్పు మరియు శనగపిండితో చేసిన రుచికరమైన పకోడీ, పార్టీలకు సరైన స్నాక్.', stock: 100 },
    { id: 'sn10', name: 'Makka Chudva', teluguName: 'మక్కా చుడ్వా', category: 'Snacks', basePrice: 300, price250g: 75, price500g: 150, price1kg: 300, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760508499/makka_snvf0m.webp', description: 'A crunchy mixture made from corn flakes, nuts, and spices.', teluguDescription: 'మొక్కజొన్న అటుకులతో చేసిన కరకరలాడే మిశ్రమం, ప్రయాణాలకు మరియు స్నాక్స్‌గా అద్భుతం.', stock: 100 },
    { id: 'sn11', name: 'Poha Chudva', teluguName: 'పోహా చుడ్వా', category: 'Snacks', basePrice: 250, price250g: 63, price500g: 125, price1kg: 250, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760508686/poha_odgohd.webp', description: 'A light and savory mixture made from flattened rice, nuts, and spices.', teluguDescription: 'అటుకులతో చేసిన తేలికపాటి మరియు రుచికరమైన మిశ్రమం, ఆరోగ్యకరమైన చిరుతింది.', stock: 100 },
    { id: 'sn12', name: 'Palli Pakoda', teluguName: 'పల్లి పకోడీ', category: 'Snacks', basePrice: 300, price250g: 75, price500g: 150, price1kg: 300, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760508813/palli_pakods_bprwea.webp', description: 'Crispy pakodas made with peanuts and a gram flour batter.', teluguDescription: 'పల్లీలు మరియు శనగపిండితో చేసిన కరకరలాడే పకోడీ, వర్షాకాలంలో తినడానికి అద్భుతంగా ఉంటుంది.', stock: 100 },
    { id: 'sn13', name: 'Besan Poori', teluguName: 'బేసన్ పూరీ', category: 'Snacks', basePrice: 300, price250g: 75, price500g: 150, price1kg: 300, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760508924/besan_s1m8ha.webp', description: 'Flavorful pooris made from gram flour, perfect with pickles and curries.', teluguDescription: 'శనగపిండితో చేసిన రుచికరమైన పూరీలు, పప్పు లేదా కూరతో తినడానికి బాగుంటాయి.', stock: 100 },
    { id: 'sn14', name: 'Mixer', teluguName: 'మిక్చర్', category: 'Snacks', basePrice: 300, price250g: 75, price500g: 150, price1kg: 300, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760509061/mixer_pw5va6.webp', description: 'A classic savory mix of various fried snacks, nuts, and spices.', teluguDescription: 'వివిధ రకాల కారపూస, బూంది మరియు పల్లీలతో చేసిన కరకరలాడే మిక్చర్.', stock: 100 },
    { id: 'sn15', name: 'Sarva Pindi', teluguName: 'సర్వపింది', category: 'Snacks', basePrice: 35, price250g: null, price500g: null, price1kg: null, unit: 'Piece', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760509724/sarvapindi_iamuni.webp', description: 'A savory pancake from Telangana made with rice flour and lentils.', teluguDescription: 'బియ్యం పిండి మరియు పప్పులతో చేసిన తెలంగాణ స్పెషల్ సర్వపింది, ఆరోగ్యకరమైన అల్పాహారం.', stock: 100 },
  
    // Spice Powders
    { id: 'sp1', name: 'Karvepaku Podi', teluguName: 'కరివేపాకు పొడి', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760515684/kari_a1s5ct.webp', description: 'Aromatic and healthy powder made from curry leaves, perfect with rice.', teluguDescription: 'కరివేపాకుతో చేసిన సువాసనగల మరియు ఆరోగ్యకరమైన పొడి, అన్నంలో కలుపుకుని తినడానికి అద్భుతం.', stock: 100 },
    { id: 'sp2', name: 'Putnala Podi', teluguName: 'పుట్నాల పొడి', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760515674/putn_l3abi1.webp', description: 'A delicious powder made from roasted gram dal, great with idli and dosa.', teluguDescription: 'పుట్నాల పప్పుతో చేసిన రుచికరమైన పొడి, ఇడ్లీ మరియు దోసెలతో తినడానికి బాగుంటుంది.', stock: 100 },
    { id: 'sp3', name: 'Palli Podi', teluguName: 'పల్లి పొడి', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760516061/palli_podi_uv8q2a.webp', description: 'A flavorful powder made from roasted peanuts, delicious with ghee and rice.', teluguDescription: 'వేయించిన పల్లీలతో చేసిన కమ్మటి పొడి, అన్నంలో నెయ్యితో కలుపుకుని తింటే రుచిగా ఉంటుంది.', stock: 100 },
    { id: 'sp4', name: 'Kandi Podi', teluguName: 'కంది పొడి', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760516309/kandhi_ch9emy.webp', description: 'A traditional powder made from toor dal, a staple with idli, dosa, and rice.', teluguDescription: 'కందిపప్పుతో చేసిన సాంప్రదాయ పొడి, ఇడ్లీ, దోసె మరియు అన్నంలోకి చాలా బాగుంటుంది.', stock: 100 },
    { id: 'sp5', name: 'Vellulli Karam', teluguName: 'వెల్లుల్లి కారం', category: 'Spice Powders', basePrice: 100, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760516516/kaaram_pduwqr.webp', description: 'A spicy and pungent powder made with garlic and red chilies.', teluguDescription: 'వెల్లుల్లి మరియు ఎండుమిర్చితో చేసిన ఘాటైన కారం, వేడి అన్నంలో నూనెతో కలిపి తింటే అద్భుతం.', stock: 100 },
    { id: 'sp6', name: 'Munagaku Podi', teluguName: 'మునగాకు పొడి', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760516643/mung_s4gt9k.webp', description: 'A healthy powder made from moringa leaves, packed with nutrients.', teluguDescription: 'మునగాకుతో చేసిన ఆరోగ్యకరమైన పొడి, పోషకాలతో నిండి ఉంటుంది మరియు అన్నంలోకి బాగుంటుంది.', stock: 100 },
    { id: 'sp7', name: 'Nuvvula Podi', teluguName: 'నువ్వుల పొడి', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760516803/nuvv_rdx6l2.webp', description: 'A tasty powder made from roasted sesame seeds, excellent with idli and dosa.', teluguDescription: 'వేయించిన నువ్వులతో చేసిన రుచికరమైన పొడి, ఇడ్లీ మరియు దోసెలతో అద్భుతంగా ఉంటుంది.', stock: 100 },
    { id: 'sp8', name: 'Idli Karam', teluguName: 'ఇడ్లీ కారం', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760517014/iildli_qkbjml.webp', description: 'A special spice powder made specifically for idlis, best served with ghee or oil.', teluguDescription: 'ఇడ్లీల కోసం ప్రత్యేకంగా తయారు చేసిన కారపొడి, నెయ్యి లేదా నూనెతో కలిపి తింటే చాలా రుచిగా ఉంటుంది.', stock: 100 },
    { id: 'sp9', name: 'Chennagaku Karam', teluguName: 'శనగాకు కారం', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760517160/chen_oomlgr.webp', description: 'A unique spice powder made from bengal gram leaves.', teluguDescription: 'శనగ ఆకులతో చేసిన ప్రత్యేకమైన కారం పొడి, అన్నంలోకి మరియు టిఫిన్స్‌లోకి రుచికరంగా ఉంటుంది.', stock: 100 },
    { id: 'sp10', name: 'Kobbari Karam', teluguName: 'కొబ్బరి కారం', category: 'Spice Powders', basePrice: 80, price250g: null, price500g: null, price1kg: null, unit: '100g', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760517694/coco_mnema4.webp', description: 'A delicious spice powder made from dried coconut and spices.', teluguDescription: 'ఎండు కొబ్బరి మరియు మసాలాలతో చేసిన కమ్మటి కారం, అన్నంలోకి చాలా బాగుంటుంది.', stock: 100 },
  
    // Pickles
    { id: 'pk1', name: 'Mango Pickle', teluguName: 'మామిడికాయ పచ్చడి', category: 'Pickles', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760517503/mango_gu2ynw.webp', description: 'The king of pickles, a traditional spicy and tangy mango pickle.', teluguDescription: 'మామిడికాయ ముక్కలతో చేసిన సాంప్రదాయ ఆవకాయ, ఊరగాయల రాజు.', stock: 100 },
    { id: 'pk2', name: 'Lemon Pickle', teluguName: 'నిమ్మకాయ పచ్చడి', category: 'Pickles', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760517915/lemon_rnxlxz.webp', description: 'A tangy and spicy pickle made from lemons, a perfect side for curd rice.', teluguDescription: 'నిమ్మకాయ ముక్కలతో చేసిన పుల్లని మరియు కారంగా ఉండే ఊరగాయ, పెరుగు అన్నంలోకి అద్భుతం.', stock: 100 },
    { id: 'pk3', name: 'Tomato Pickle', teluguName: 'టమాటా పచ్చడి', category: 'Pickles', basePrice: 400, price250g: 100, price500g: 200, price1kg: 400, unit: '1KG', image: 'https://res.cloudinary.com/duhabjmtf/image/upload/v1760518212/toma_tr2b8y.webp', description: 'A delicious pickle made from tomatoes, great with rice, chapati, and dosa.', teluguDescription: 'టమాటా ముక్కలతో చేసిన రుచికరమైన ఊరగాయ, అన్నం, చపాతీ మరియు దోసెలతో బాగుంటుంది.', stock: 100 },
];

async function seedDatabase() {
  try {
    console.log('Connecting to database...');
    await connectDB();
    
    console.log('Syncing database...');
    await sequelize.sync({ force: false }); // Use force: true to drop and recreate tables
    
    console.log('Seeding products...');
    
    for (const product of productsData) {
      const existingProduct = await Product.findByPk(product.id);
      
      if (existingProduct) {
        console.log(`Product ${product.id} already exists, skipping...`);
      } else {
        await Product.create(product);
        console.log(`✓ Added product: ${product.name} (${product.id})`);
      }
    }
    
    console.log('\n✅ Database seeding completed successfully!');
    console.log(`Total products in database: ${await Product.count()}`);
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();